# Generated by Django 3.2 on 2021-05-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contacts',
            new_name='contact',
        ),
    ]
