# Generated by Django 3.2 on 2021-05-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0002_rename_contacts_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=122)),
                ('Email', models.CharField(max_length=122)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
